### PR TITLE
Data integration

### PR DESCRIPTION
**Pull request by cskiraly**
Integration of agile-data and related UI elements

### CODE REVIEW

**Comment by Exulansis** [comment]
A number of small fixes are needed before this can be merged, the roadmap (in chronological sequence) is:
- [ ] Solve merge conflict.
- [ ] This Agile Data [pull request](https://github.com/Agile-IoT/agile-data/pull/25) has to merged.
- [ ] This Agile SDK [pull request](https://github.com/Agile-IoT/agile-data/pull/25) has to be merged, or the corresponding [issue](https://github.com/Agile-IoT/agile-sdk/issues/33) addressed in any fitting way.
- [ ] Make sure that Agile UI uses the (to be updated) version of the Agile SDK.
- [ ] Update the docker-compose file to make use of the new / fixed version of Agile Data.

**Comment by Exulansis** [comment]
@craig-mulligan Could you please publish the new version of the agile sdk (v1.2.1), so that it can be referenced in the Agile UI? Thank you!

**Comment by Exulansis** [comment]
All aforementioned steps are done, I am doing a round of testing and once that is done, merging can happen.

**Comment by Exulansis** [comment]
The integration is completed, the Data-Ui parts are tested and work (assuming that the underlining agile-core stack functions well), @nopbyte could you please do a quick test run of your parts as well, I've seen they load and display fine, the tokens are passed as intended, but I haven't tested all possible interactions, thank you!

**Comment by nopbyte** [comment]
hi @Exulansis,
I am going to checkout the PR and try it out. I will report back when I know how it went,

**Comment by nopbyte** [comment]
hi @Exulansis,

I tested a bit and things seem to work as expected from the security side with the UI.

**Comment by Exulansis** [comment]
Good news, then I will proceed and merge this into the base branch.

**Pull request merged**
