### PR TITLE
0.2.0-rc

### PR DESCRIPTION
**Pull request by cskiraly**
0.2.0 with security weaved in

Adding agile-security, and updating agile-osjs, agile-nodeded.

### CODE REVIEW

**Comment by nopbyte** [comment]
When I try to open the device manager. I cannot see the type of device for dummy to register it.

The logs show this:
```
agile-core        | 12:30:42.830 [qtp23325099-13] DEBUG iot.agile.http.service.DbusClient - Load cached object iot.agile.ProtocolManager:/iot/agile/ProtocolManager
agile-core        | 12:30:42.830 [qtp23325099-13] DEBUG iot.agile.http.service.DbusClient - Load cached object iot.agile.ProtocolManager:/iot/agile/ProtocolManager
agile-core        | 12:30:42.833 [qtp23325099-13] ERROR i.a.h.exception.AgileExceptionMapper - Error occured
agile-core        | org.freedesktop.dbus.exceptions.NotConnected: Not Connected
agile-core        | 	at org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(Unknown Source)
agile-core        | 	at org.freedesktop.dbus.RemoteInvocationHandler.invoke(Unknown Source)
agile-core        | 	at com.sun.proxy.$Proxy35.Devices(Unknown Source)
agile-core        | 	at iot.agile.http.resource.ProtocolManager.Devices(ProtocolManager.java:70)
agile-core        | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
agile-core        | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
agile-core        | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
agile-core        | 	at java.lang.reflect.Method.invoke(Method.java:498)
agile-core        | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
agile-core        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
agile-core        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
agile-core        | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
agile-core        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
agile-core        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
agile-core        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
agile-core        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
agile-core        | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
agile-core        | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
agile-core        | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
agile-core        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
agile-core        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
agile-core        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
agile-core        | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
agile-core        | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
agile-core        | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
agile-core        | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
agile-core        | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
agile-core        | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
agile-core        | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
agile-core        | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
agile-core        | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
agile-core        | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
agile-core        | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
agile-core        | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
agile-core        | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
agile-core        | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
agile-core        | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
agile-core        | 	at org.eclipse.jetty.server.Server.handle(Server.java:524)
agile-core        | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
agile-core        | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
agile-core        | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
agile-core        | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
agile-core        | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
agile-core        | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
agile-core        | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
agile-core        | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
agile-core        | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
agile-core        | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
agile-core        | 	at java.lang.Thread.run(Thread.java:745)
agile-ble         | 12:30:43.045 [pool-1-thread-1] DEBUG i.agile.protocol.ble.BLEProtocolImp - Checking for new devices

```
Did we introduce this behaviour with the versions?

**Comment by cskiraly** [comment]
Is this reproducible? ARM or x86_64? Seems like the ProtocolManager not being accessible on the D-Bus, or agile-http being disconnected from the D-Bus.

**Comment by nopbyte** [comment]
AFAIK, I just updated the agile-stack, removed idm security metadata and executed compose up. 
I could delete all the containers, the data folder and do the compose up again. Do you think this is needed to be sure that it is reproducible?
I am running it on a rpi3

**Comment by cskiraly** [comment]
What might be missing from your steps is to force pull new versions of 
containers. Can you try an `agile update`?

**Comment by nopbyte** [comment]
Docker version 17.05.0-ce
OS:
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

**Comment by cskiraly** [comment]
@craig-mulligan, can you have a look at this? I think we still have a mismatch between UI and core, but I can't check right now. I suppose the fix is needed more in the core, but it would be nice to narrow down a way to trigger the problems.

**Comment by craig-mulligan** [comment]
@cskiraly @nopbyte 
Hmm, so this has the security in the api right? The UI shouldn't work in this case because it doesn't have a token?

With regards to the error ~ i don't have any theories atm, possible that the ui is making request that cause the http error to fail and loose connection with the protocolmanager? is that possible? 

I'll try get this v running on resinos now, but @nopbyte in the meantime can you try running the containers without the ui open (so no requests are made to the api) and see if the same error occurs? that'll rule out the ui's involvement.

**Pull request merged**
