### PR TITLE
Add recommender and configurator

### PR DESCRIPTION
**Pull request by craig-mulligan**
Connects to #25

Change-Type: patch

### CODE REVIEW

**Comment by SedaPolatErdeniz** [comment]
+    container_name: agile-recommenderandconfigurator  -> OK
 +    image: agileiot/recommenderandconfigurator:v1.0 -> OK
 +    # build: apps/agile-recommenderandconfigurator -> OK
 +    restart: always -> OK
 +    ports: -> OK
 +      - 8090:8090/tcp -> OK

**Comment by cskiraly** [comment]
@SedaPolatErdeniz is there a way to test functionality after integration?

**Comment by cskiraly** [comment]
This should be merged into branch master, not into rm-push-cmd

**Comment by cskiraly** [comment]
@SedaPolatErdeniz @craig-mulligan where is the repo with the Dockerfile?

**Pull request merged**
